version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "python create_tables.py &&
             python app.py"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Goga
      POSTGRES_PASSWORD: 191202
      POSTGRES_DB: db_errors
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
