version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "python create_tables.py &&
             python app.py"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Goga
      POSTGRES_PASSWORD: 191202
      POSTGRES_DB: db_errors
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
