"""Increase action_type length to 50

Revision ID: 21632c2dd1ec
Revises: 9d2e4b9f9535
Create Date: 2025-02-20 14:31:22.112250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21632c2dd1ec'
down_revision = '9d2e4b9f9535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
