"""Add type field as string to ErrorImage

Revision ID: 95b7a50460ff
Revises: b69f6a4f7c96
Create Date: 2025-02-17 11:40:38.875939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b7a50460ff'
down_revision = 'b69f6a4f7c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_image', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
