"""Add error_id column to admin_log

Revision ID: 9d2e4b9f9535
Revises: 5b38437e81a2
Create Date: 2025-02-20 14:23:26.327521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2e4b9f9535'
down_revision = '5b38437e81a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('action_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'error', ['error_id'], ['id'])
        batch_op.drop_column('action')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('details')
        batch_op.drop_column('action_type')
        batch_op.drop_column('error_id')

    # ### end Alembic commands ###
